# Generated by Django 4.2.1 on 2023-05-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_image_remove_post_view_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.TextField(null=True, verbose_name='분류'),
        ),
    ]
