# Generated by Django 4.2.1 on 2023-05-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_category_alter_post_image_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='썸네일'),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(null=True, verbose_name='평점'),
        ),
    ]
