# Generated by Django 4.2.1 on 2023-05-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_image_alter_post_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='post_photo', verbose_name='썸네일'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
