# Generated by Django 4.2.1 on 2023-05-19 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_image_post_photo_delete_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='conmment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='create_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='target_post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='writer',
        ),
    ]
