# Generated by Django 4.2.1 on 2023-05-25 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_comment_conmment_comment_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='target_post',
            new_name='article',
        ),
    ]
