# Generated by Django 4.2.1 on 2023-06-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scrap',
            field=models.ImageField(null=True, upload_to='', verbose_name='게시글스크랩'),
        ),
    ]
