# Generated by Django 4.2.1 on 2023-06-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_scrap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='post_photo', verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='post',
            name='scrap',
            field=models.IntegerField(null=True, verbose_name='게시글스크랩'),
        ),
    ]
