# Generated by Django 4.2.1 on 2023-06-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_post_photo_alter_post_scrap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='scrap',
            field=models.BooleanField(default=False, verbose_name='게시글스크랩'),
        ),
    ]
