# Generated by Django 4.2.1 on 2023-06-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_remove_post_scrap_post_save'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_save',
            new_name='Scrap',
        ),
    ]
